### ISSUE TITLE
Error running XAVIER on frce

### ISSUE THREAD

**Issue by samarth8392** [CCBR/XAVIER#31]
### `xavier v2.0` stable release on biowulf does not work on FRCE. 

1. Created a new branch `frce_test` from  XAVIER `main` to test on frce.
2. Cloned the repo and created a file `config/cluster.frce.json` which does not have `gres` argument.
3. Since `--tmp_dir` is `/lscratch/\$SLURM_JOBID/` by default on biowulf, we need to provide `/scratch/cluster_scratch/\$USER/` on frce.
4. Ran the pipeline as follows:

```
/scratch/cluster_scratch/mathurs2/XAVIER/xavier run \
--input data/*.R?.fastq.gz \
--output runs/hg38.cli.tp.r1 \
--genome hg38 \
--pairs pairs.txt \
--tmp-dir /scratch/cluster_scratch/$USER/ \
--targets Twist_Exome_Core_Covered_Targets_hg38.bed \
--mode slurm \
--runmode init 
```
No error during initialization but when I do `--runmode dryrun`, I get the following error:
```
xavier (v2.0)
--Dry-Run
Command '['snakemake', '-npr', '-s', 'workflow/Snakefile', '--use-singularity', '--cores', '1', '--configfile=config.json']' returned non-zero exit status 1. b'ImportError in file /scratch/cluster_scratch/mathurs2/techDev/runs/hg38.cli.tp.r1/workflow/Snakefile, line 6:\nUnable to import required dependencies:\nnumpy: \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.10 from "/mnt/nasapps/production/snakemake/mambaforge/bin/python3.10"\n  * The NumPy version is: "1.24.1"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: No module named \'numpy.core._multiarray_umath\'\n\n  File "/scratch/cluster_scratch/mathurs2/techDev/runs/hg38.cli.tp.r1/workflow/Snakefile", line 6, in <module>\n  File "/mnt/nasapps/production/python/3.11/lib/python3.11/site-packages/pandas/__init__.py", line 16, in <module>\n'
Traceback (most recent call last):
  File "/scratch/cluster_scratch/mathurs2/XAVIER/xavier", line 731, in <module>
    main()
  File "/scratch/cluster_scratch/mathurs2/XAVIER/xavier", line 727, in main
    args.func(args)
  File "/scratch/cluster_scratch/mathurs2/XAVIER/xavier", line 115, in run
    dryrun_output = dryrun(outdir = sub_args.output) # python3 returns byte-string representation
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/cluster_scratch/mathurs2/XAVIER/src/run.py", line 614, in dryrun
    raise(e)
  File "/scratch/cluster_scratch/mathurs2/XAVIER/src/run.py", line 594, in dryrun
    dryrun_output = subprocess.check_output([
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nasapps/production/python/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nasapps/production/python/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snakemake', '-npr', '-s', 'workflow/Snakefile', '--use-singularity', '--cores', '1', '--configfile=config.json']' returned non-zero exit status 1.

```

**Comment by samarth8392** [comment]
The error was due to a bug on FRCE cluster based on which versions of snakemake and singularity is set to default on `norm` vs `norm-oel8` node. 
on `norm`:
```
$module purge
$module load singularity snakemake
[+] Loading singularity 3.9.7
[+] Loading python 3.7.7
[+] Loading snakemake 7.3.8
```
on `norm-oel8`:
```
[+] Loading singularity 3.10.5
[+] Loading snakemake 7.20.0
```

**Solution** : Only use `norm` partition for running the pipeline and let FRCE team know about the difference in module load behavior

**Comment by samarth8392** [comment]
Also see #18 (i think it's the same/similar problem)
